site_name: "@jonchun"
site_url: https://blog.jonathanchun.com/
theme:
  name: material
  palette:
    primary: deep_orange
    accent: amber
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
  - index.md

# Theme configuration
theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
  - navigation.instant
  - navigation.tracking
  - toc.follow
  - content.code.copy
  - content.code.annotate

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: black
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: blue
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

# Plugin configuration
plugins:
- search
- blog:
    blog_dir: .
    archive_date_format: MMMM yyyy
    archive_url_date_format: yyyy/MM
    pagination_per_page: 1
    pagination_url_format: "{page}"
    pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"

- rss:
    match_path: posts/.* 
    date_from_meta:
      as_creation: date.created
    categories:
      - categories
      - tags
- social

# Markdown extensions
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-T9PSHZN9VJ