site_name: "@jonchun"
site_url: https://jonchun.github.io/
theme:
  name: material
  palette:
    primary: deep_orange
    accent: amber
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
  - Blog:
    - blog/index.md

# Theme configuration
theme:
  name: "material"
  features:
  - navigation.instant
  - navigation.tracking
  - toc.follow
  - content.code.copy
  - content.code.annotate

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: black
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: blue
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

# Plugin configuration
plugins:
- search
- blog
- rss:
    match_path: blog/posts/.* 
    date_from_meta:
      created: date
    categories:
      - categories
      - tags

# Markdown extensions
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-C4FTHDBGRX