[project]
name = "blog"
version = "0.1.0"
description = "Jonathan Chun's blog"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mkdocs-material[imaging]>=9.6.3", "mkdocs-rss-plugin>=1.17.1"]
